### ISSUE TITLE
이미지 에디터 테스트 세팅

### ISSUE THREAD

**Issue by bakhwee-bug** [SS507-today/project-today-flutter#3]
## 📌 어떤 EPIC/Milestone 인가요?
이미지 에디터 테스트 세팅

## 🗓️ Due date
0806

## 🌈 Feature List

- [ ] 라이브러리 추가
- [ ] test_screens.dart

## ✅ Check List

- [ ] 담당자 등록
- [ ] 라벨 등록 `EPIC`
- [ ] DDL 체크

**Comment by kweonsikyung** [comment]
와 기대돼요 ㄷㄷ
